### ISSUE TITLE
Remove Firebase hostnames from mentioned blcoklists

### ISSUE THREAD

**Issue by varun-shtech** [safehousetech/Activedefence#1]
@kapilsingh421 Hostnames to remove:

1.
[firebase-settings.crashlytics.com](http://firebase-settings.crashlytics.com/)
[firebaselogging.googleapis.com](http://firebaselogging.googleapis.com/)

from

https://raw.githubusercontent.com/safehousetech/Activedefence/master/GoodbyeAds.txt

2.
[firebaselogging.googleapis.com](http://firebaselogging.googleapis.com/)

From 

https://raw.githubusercontent.com/safehousetech/Activedefence/master/StevenBlack.txt

3.
[firebase-settings.crashlytics.com](http://firebase-settings.crashlytics.com/)
[firebaselogging.googleapis.com](http://firebaselogging.googleapis.com/)
[test.firebaselogging.googleapis.com](http://test.firebaselogging.googleapis.com/)

From

https://raw.githubusercontent.com/safehousetech/Activedefence/master/ads-and-tracking-extended.txt

4.
[firebasedynamiclinks-ipv4.googleapis.com](http://firebasedynamiclinks-ipv4.googleapis.com/)
[firebaselogging.googleapis.com](http://firebaselogging.googleapis.com/)  From

https://raw.githubusercontent.com/safehousetech/Activedefence/master/ads.txt

5.
[firebase-settings.crashlytics.com](http://firebase-settings.crashlytics.com/)
[firebaselogging.googleapis.com](http://firebaselogging.googleapis.com/)

From

https://raw.githubusercontent.com/safehousetech/Activedefence/master/energized.txt

6.
[firebase.com](http://firebase.com/)

From

https://github.com/safehousetech/Activedefence/blob/master/exodusprivacy.txt

7.
[firebaselogging.googleapis.com](http://firebaselogging.googleapis.com/)

From

https://github.com/safehousetech/Activedefence/blob/master/someonewhocares.txt

**Comment by kapil-tftus** [comment]
removed host
